use_frameworks!

target :BLDashboard, :exclusive => true do
  platform :ios, '9.0'
  pod 'Riffle'
  pod 'KYCircularProgress'
  pod 'SVProgressHUD'
  pod 'SCLAlertView'
end

target :Backend, :exclusive => true do
  platform :osx, '10.10'
  pod 'Riffle'
end
